### ISSUE TITLE
Sonar_convention_version should be incremented

### ISSUE THREAD

**Issue by geoffmatt** [ices-publications/SONAR-netCDF4#29]
The version for a format definition like this should be incremented for any breaking change.
Currently the format is still on version 1.0. I appreciate that officially the format is not released at the moment, and is still in development, but even so the version needs to be updated. 
There are people writing files to this definition and it will become increasingly difficult to read these files if we cannot identify the specific version of the format to which they were created.

**Comment by cyrilleponcelet** [comment]
I agree with that, a lot of things changed since v 1.0
We could at least change the second digit.
I'll make a pull request for it, do you think we need any release note for the development version ou do you think git history is good enough?

**Comment by geoffmatt** [comment]
I think the GIT history is good enough for me. Ideally I'd like the minor version to be incremented for any potentially breaking change

**Comment by gavinmacaulay** [comment]
I was thinking that the version could be increased to 2.0, given the significant changes to the format and, in particular, the support for echosounders, ADCP's, multibeams, etc. 

Another remaining thing with this is how to integrate this with ICES's editorial process.

**Comment by geoffmatt** [comment]
I think this one's interesting, given the open source nature of it. 
At Echoview we'd increment a minor version number for absolutely any change, irrespective of how small it is. That way if we see problems from a user we can identify the exact version they've been using. But we have set dates when we issue updates to the outside world so it's easier to handle. 
For an open source format, I'm not sure who's responsible for incrementing the version, or how that'd be enforced
