### ISSUE TITLE
Definition of sample_t type for backscatter data in BeamGroup rather than in SonarGroup

### ISSUE THREAD

**Issue by lberger29** [ices-publications/SONAR-netCDF4#37]
Currently sample_t type is defined in SonarGroup and can be set as:
- short for backscatter values in Power or Sv
- float for complex samples

This sample_t type should rather be defined in BeamGroup allowing storage of both types of data when running echosounders with multiple transducers using both CW and FM

**Comment by gavinmacaulay** [comment]
Agreed. Please provide a PR to make this change.

**Comment by lberger29** [comment]
@gavinmacaulay this can be closed
