### ISSUE TITLE
Need for angle clarification

### ISSUE THREAD

**Issue by cyrilleponcelet** [ices-publications/SONAR-netCDF4#4]
Hi everyones, 
I got one question, do you think that the angles definition (rx_beam_rotation_phi and consort) are clear enough. 
I mean do think that we need to add more information to clearly explain to which coordinate system angles are relative to (ie vertical or tx array) ? Or do you think that what is written in table 3 is enough ?

> |Transducer coordinate system (TCS) |Centre of transducer face|||
> 2+|_not stabilized_ |Pointing forward along transducer plane|Pointing starboard along transducer plane|Pointing down orthogonal to transducer plane
> 2+|_stabilized_ |Pointing forward along transducer plane|Pointing horizontally and perpendicular to x-axis|Pointing down with gravity

**Comment by gavinmacaulay** [comment]
One can never be too clear :) If we think that this is an area that might cause confusion, I think we should then provide very clear explanations and even examples (we can do this for rx_beam_rotation_phi, etc).

Should the x-axis for stabilized say 'pointing forward horizontally'?

**Comment by cyrilleponcelet** [comment]
> Should the x-axis for stabilized say 'pointing forward horizontally'?
You're probably right. for stabilized system only

**Comment by cyrilleponcelet** [comment]
see pull request #5

**Comment by gavinmacaulay** [comment]
Pull request #5 accepted, so closing this.
