### ISSUE TITLE
Add SONAR-netCDF4 to fairsharing.org

### ISSUE THREAD

**Issue by emiliom** [ices-publications/SONAR-netCDF4#43]
https://fairsharing.org is a great resource for finding and briefly -- but systematically -- describing all sorts of data and metadata standards. A [search on "sonar"](https://fairsharing.org/search/?q=sonar) doesn't generate any results. It'd be great to add SONAR-netCDF4; I'd be happy to help with that. Though, unfortunately, the ability to add new entries is disabled until September due to a system upgrade.

Note that there is one ICES resource listed at https://fairsharing.org: The ["ICES Data Portal"](https://fairsharing.org/FAIRsharing.4TCb1c).

**Comment by gavinmacaulay** [comment]
Great idea! Please help with that once they finish their upgrade.

**Comment by gavinmacaulay** [comment]
@emiliom Are you still offering to add SONAR-netCDF4 to fairsharing? No problems if not - I'll then have a go.

**Comment by emiliom** [comment]
Yes, I can still do it if you haven't done it already. I can tackle it this week or next.

**Comment by gavinmacaulay** [comment]
I had some time, so have added it to fairsharing. It is current under review.
