### ISSUE TITLE
Consider a way to specify which types of data should be created from the file (TS, Sv etc)

### ISSUE THREAD

**Issue by geoffmatt** [ices-publications/SONAR-netCDF4#60]
Currently all the specified equations are designed to allow both TS and Sv data to be generated from the file.
This is entirely sensible for files which are being generated by an echosounder or sonar, however it is slightly problematic for files generated by post processing software.
For example if we load a NetCDF file into Echoview we will generate TS and Sv variables for each Sonar Group, as expected.
However the user can then export just the Sv data from Echoview to another NetCDF file.
If that file is loaded then, again we have to generate TS and Sv variables from it. It would be useful for us to only generate the Sv data which was exported.
We are going to primarily be exporting to the Type 5 equation, so we might be able to solve this by only exporting the Sv or TS data, and leaving the other blank. But that it making an assumption that for Type 5 files, if only one data type is included, then only that data type should be created.
Does that make sense?

**Comment by geoffmatt** [comment]
Yeah that was what I was thinking, make it compliant to have TS or Sv only, or both.
That way we could use the presence of each data set as the key to creating that data when the file was loaded. 
Otherwise we would need a different variable stating which data options to create when the file was loaded. That is what our file format does to solve the same problem, but it would mean adding a new variable which seems like overkill in this case.

**Comment by gavinmacaulay** [comment]
Checking off issues and I think this was addressed in c5deb7fddfe8f764dafb9b05af3625b67ae3b4d3. Reopen if not.
