### ISSUE TITLE
The time standard for conversion_time is different to date_created

### ISSUE THREAD

**Issue by geoffmatt** [ices-publications/SONAR-netCDF4#66]
There are two date/time stamps within the standard:
date_created in the Top level group
conversion_time in the Provenance group

These currently are not using the same ISO standard, date_created uses ISO8601:2004 whereas conversion_time uses ISO8601:2005. The latter should probably never be used as I believe it was withdrawn. Either way the two should be the same as they have differences which mean that the same code cannot read both.

**Comment by gavinmacaulay** [comment]
Corrected in #67
