### ISSUE TITLE
Minor issue : equation not rendered

### ISSUE THREAD

**Issue by cyrilleponcelet** [ices-publications/SONAR-netCDF4#69]
Might be a github renderer issue but on the htmlpreview The equation just before §5.3.1 is not well rendered

![image](https://user-images.githubusercontent.com/30068854/153423273-3eb666f7-e7d2-4b5d-9a55-9efba4577de1.png)

If you can check on the final document.

**Comment by gavinmacaulay** [comment]
Fixed in 6148cfb050542c4583c42beb60ef7fdb11923767.
