### ISSUE TITLE
Missing paragraph for gridded data

### ISSUE THREAD

**Issue by cyrilleponcelet** [ices-publications/SONAR-netCDF4#71]
Hi @gavinmacaulay , 
we just noticed with @lberger29  that the reference to gridded data is in fact in a [3.10.6. Proposed ADCP additions](https://github.com/ices-publications/SONAR-netCDF4/blob/master/docs/crr341.adoc#3106-proposed-adcp-additions)

Furthermore the [tableBeamGridGroup1.adoc](https://github.com/ices-publications/SONAR-netCDF4/blob/master/docs/tableBeamGridGroup1.adoc) file is referenced nowhere else in the main document.

We will come soon with a merge request to fix this, I think this should be done before any official release as a 2.0 version of the document.

**Comment by gavinmacaulay** [comment]
Nice find! I had started to wonder where the grid stuff was in the document...
