### ISSUE TITLE
Example gridded data set

### ISSUE THREAD

**Issue by nilsolav** [ices-publications/SONAR-netCDF4#83]
Hi,

I am writing code to generate a gridded data set, and would like to follow the convention. 

I have an xarray object that I would like to write to nc.

Do someone have a test data set that I can use when trying to set this up?

Nils Olav

**Comment by lberger29** [comment]
Hello Nils Olav,
I have uploaded two gridded SonarNetCdf files [here ](https://filesender.renater.fr/?s=download&token=fcc28843-f420-453e-a1fb-44a6992b01f3) (available two weeks) from our WGFAST presentation comparing Europe vessel and Drix USV.
You can also visualize these files in a geographic environment with our GLOBE software available [here](https://www.seanoe.org/data/00592/70460/).
Laurent
