### ISSUE TITLE
ICES has moved their library

### ISSUE THREAD

**Issue by ivarwa** [ices-publications/SONAR-netCDF4#85]
Version 1 of the SONAR-netCDF4 document can now be found here: [https://ices-library.figshare.com/articles/report/The_SONAR-netCDF4_convention_for_sonar_data_Version_1_0/18624056](https://ices-library.figshare.com/articles/report/The_SONAR-netCDF4_convention_for_sonar_data_Version_1_0/18624056)

**Comment by gavinmacaulay** [comment]
Thanks. Fixed now in #222223d01fa557248f94515fa3de69d6f4ccdd69
